services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

  redis:
    ports: !reset []

  db:
    ports: !reset []

  node:
    profiles:
      - build
